# application-dev.yml
spring:
  datasource:
    url: ${DEV_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

