# application-prod.yml
spring:
  datasource:
    url: ${PROD_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

